### ISSUE TITLE
Websites behind CDN show only Cloudflare IP addresses

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ip#5]
Probably something needs to be configured on either CloudFlare or webserver (Apache), so Backdrop sees the visitors' original IP addresses, in order to address the issue in the subject. But I thought maybe the module's maintainers or someone knows better what exactly needs to be done. Thanks!

**Comment by alanmels** [comment]
Ok, all who hit this issue should be reading this tutorial: https://developers.cloudflare.com/support/troubleshooting/restoring-visitor-ips/restoring-original-visitor-ips/

**Comment by bugfolder** [comment]
@alanmels, I've looked at the tutorial you linked, but it's pretty heavy going. I'm wondering if we should add a line or two to the README to make it easier for people afflicted by this issue to catch it proactively, and if so, would you be interested in drafting a line or two that might give people a heads-up?

**Comment by alanmels** [comment]
I could only share what I did to get this working on a Fedora-based operating system, so Debian-like systems would have slightly different steps.

1. Open the `/etc/httpd/conf/httpd.conf` file, find the respective website's entries and add the `RemoteIPHeader CF-Connecting-IP` line as in a given example:

```
ServerAdmin webmaster@localhost
DocumentRoot /var/www/html
ServerName remoteip.andy.support
RemoteIPHeader CF-Connecting-IP
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined
```

2. Replace all occurrences of `%h` with `%a` in the same  `/etc/httpd/conf/httpd.conf` file.

3. Create a file /etc/httpd/conf.modules.d/10-cloudflare.conf and paste the following content:

```
RemoteIPHeader CF-Connecting-IP
RemoteIPTrustedProxy 173.245.48.0/20
RemoteIPTrustedProxy 103.21.244.0/22
RemoteIPTrustedProxy 103.22.200.0/22
RemoteIPTrustedProxy 103.31.4.0/22
RemoteIPTrustedProxy 141.101.64.0/18
RemoteIPTrustedProxy 108.162.192.0/18
RemoteIPTrustedProxy 190.93.240.0/20
RemoteIPTrustedProxy 188.114.96.0/20
RemoteIPTrustedProxy 197.234.240.0/22
RemoteIPTrustedProxy 198.41.128.0/17
RemoteIPTrustedProxy 162.158.0.0/15
RemoteIPTrustedProxy 104.16.0.0/13
RemoteIPTrustedProxy 104.24.0.0/14
RemoteIPTrustedProxy 172.64.0.0/13
RemoteIPTrustedProxy 131.0.72.0/22
RemoteIPTrustedProxy 2400:cb00::/32
RemoteIPTrustedProxy 2606:4700::/32
RemoteIPTrustedProxy 2803:f800::/32
RemoteIPTrustedProxy 2405:b500::/32
RemoteIPTrustedProxy 2405:8100::/32
RemoteIPTrustedProxy 2a06:98c0::/29
RemoteIPTrustedProxy 2c0f:f248::/32
```

4. Restart Apache and enjoy all the original IPs rolling into the logs of your Backdrop website.
