### ISSUE TITLE
Provide more information on IP

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ip#7]
Would be nice if clicking on IP and going to https://website/user/uid/ip we could find more information on IP address like country, state, etc. See, for example, https://www.infobyip.com. Maybe use some code that some other modules that operate geolocation like, for example, https://github.com/backdrop-contrib/languageicons use.

**Comment by bugfolder** [comment]
This feels like a job for a submodule (or a separate helper module), since a user might want to use any of several geocoding services. The `user/UID/ip` page is a View, so the support module could create additional Views handler(s), and then the user could easily add the desired columns to the View in their installation.

**Comment by alanmels** [comment]
Not to complicate things, the module could provide a simple link to https://www.infobyip.com/ip-x.x.x.x.html, where x.x.x.x is the logged IP and admins could just go to infobyip.com to look for additional information.

**Comment by bugfolder** [comment]
Well, that's actually doable right now:

* Edit the View "IP addresses by user".
* Add a field of type "Global: custom text".
* Set the text to "infobyip" (or anything you want)
* Under "Rewrite results," check the "Output this field as a link" checkbox.
* For the "Link path", use https://www.infobyip.com/ip-[ip].html. (Note the token [ip].)
* Check the "External server URL" checkbox.
* Save.

Now the View at user/UID/ip has a new column, that when you click on it, it takes you to the relevant infobyip.com page.

**Comment by alanmels** [comment]
Didn't think this through to see this very simple solution. Thank you very much!
